### ISSUE TITLE
refactor : dto 수정 / 토큰 추가

### ISSUE THREAD

**Issue by singsangssong** [TG-WinG/tech-blog#10]
# Title

- title

# TODO

- [x] 회원가입 완료시 바로 로그인 될 수 없도록 함.
- [x] dto 전체 점검
- [x] 티지윙 디비 따로 생성
- [x] 메인페이지에서 이름, 프로필사진 전달

# etc

- nothing
